[project]
name = "asteroids"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pygame>=2.6.1",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "pyright>=1.1.394",
    "pytest>=8.3.4",
    "ruff>=0.9.7",
]
